
lb-web:
  ports:
  - 80:8080
  tty: true
  image: rancher/load-balancer-service
  links:
  - web:web
  stdin_open: true
    
web:
  environment:
    SPRING_DATA_MONGODB_HOST: mongo
    SPRING_DATA_MONGODB_PORT: '27017'
  labels:
    io.rancher.container.pull_image: always
  image: dshiplet/jhipster_upload
  
mongo:
  image: mongo
